### ISSUE TITLE
在使用datePicker时,天数部分均为31天,当前月份实际没有31天的话,点击确定会Crash

### ISSUE THREAD

**Issue by nene-nj** [qyfeng009/QTimePicker#3]

**Comment by NJGEGE** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by nene-nj** [comment]
初始化时

**Comment by qyfeng009** [comment]
收到 BUG, 多谢！
BUG 原因： 在初始化取数据时 pickerView 取的是最小的时间范围，即1958年1月的数据，因此在第一次渲染数据时取得是1958年1月的数据，而在之后进行重置数据时 即 resetDateShow 方法中 pickerView.selectRow(indexArray[i], inComponent: i, animated: true) 进入 didSelectRow的方法中，对应的数据没有改变，故出现的这个BUG。
解决方法： 在 resetDateShow 方法中添加 pickerView(pickerView, didSelectRow: indexArray[i], inComponent: i) 方法，让他在滚动后进入 didSelectRow 方法中改变数据
